### ISSUE TITLE
Wemos D1

### ISSUE THREAD

**Issue by andibacken** [matlen67/soyosource-powercontroller#14]
Läuft das Projekt auch auf einem Wemos?

Habe es geflasht, kann mich verbinden und komme auch ins Menü. Wenn ich das WiFi einrichten will, bleibt die Seite allerdings leer. Am Browser liegt es nicht.

Die Infoseite zeigt alles wunderbar an.

**Comment by matlen67** [comment]
Kann ich garnicht genau sagen, habe keinen Wemos D1 da.

**Comment by Gerri1** [comment]
Ja, läuft auf einem Wemos!

**Comment by andibacken** [comment]
> Ja, läuft auf einem Wemos!

Klingt ja erstmal gut.. aber dann ist es um so merkwürdiger das die WiFi Seite weiß bleibt.

Probiert hab ich mit Chrome, Firefox, Edge und Handy.. überall das selbe Phänomen.

**Comment by matlen67** [comment]
Wie bzw. womit hast Du geflasht?

**Comment by matlen67** [comment]
Habe mir nun einen Wemos D1 mini über AZ-Delivery bestellt [](https://www.az-delivery.de/products/d1-mini) , der ist gerade gekommen. Geflasht über platformio, Wlan config durchgeführt, er startet neu und das Webif ist auch verfügbar. Keine Ahnung was da bei dir los ist. War da schon mal ne andere Soft drauf? Evtl. mal über die Arduino IDE ein leeres Programm drauf flashen mit der einstellung Erase Flash -> All flash Contents.

**Comment by Gerri1** [comment]
Bei den 8266er nehme ich immer den Tasmotizer, hatte damit noch keine Probleme!

**Comment by andibacken** [comment]
Habe mit Tasmotizer und Flashesp8266 geflasht.

Der Wemos war schon mal mit was anderem geflasht.
Hatte sogar zwei Stück probiert.. aber alles alte Dinger.

Neue sind unterwegs. Ich werd's nochmal versuchen.

Vielen Dank bis hier hin!

**Comment by andibacken** [comment]
Hatte Version 1.24.0426 geflasht..

Bin jetzt bei 1.240819. Siehe da, funktioniert!

Allerdings wird die RS485 Verbindung nicht aufgebaut.. lief bis dato mit der Software von BSG. Da wurde die Verbindung hergestellt.. allerdings funktionierte da nur die Händische Eingabe, die Nullregelung funktioniert da auch nicht.

**Comment by TronTronix** [comment]
Ich weiß jetzt nicht wie es aufgebaut ist bei dir aber wenn du von der Software von BSG kommst ist die Hardware Verbindung auch anders zu diesen Projekt.

ohne eine Hardware Änderung muß das in der Software geändert werden. (main.cpp)

```
char dbgbuffer[128]; 

// #define RXPin        D1  // Serial Receive pin (D1)
// #define TXPin        D4  // Serial Transmit pin (D4)
// Tron
#define RXPin        RX  // Serial Receive pin (RX)
#define TXPin        TX  // Serial Transmit pin (TX)

```
Ich arbeite mit ein WeMos D1 mini Pro und den Orginal Stromzähler mit Hichi Lesekopf und Tasmota in SML.

**Comment by andibacken** [comment]
> Ich weiß jetzt nicht wie es aufgebaut ist bei dir aber wenn du von der Software von BSG kommst ist die Hardware Verbindung auch anders zu diesen Projekt.
> 
> ohne eine Hardware Änderung muß das in der Software geändert werden, damit es kompatibel zur alten Verdrahtung zur BSG ist. (main.cpp)
> 
> ```
> char dbgbuffer[128]; 
> 
> // #define RXPin        D1  // Serial Receive pin (D1)
> // #define TXPin        D4  // Serial Transmit pin (D4)
> // Tron
> #define RXPin        RX  // Serial Receive pin (RX)
> #define TXPin        TX  // Serial Transmit pin (TX)
> ```
> 
> Ich arbeite mit ein WeMos D1 mini Pro und den Orginal Stromzähler mit Hichi Lesekopf und Tasmota in SML.

Pins ebend umgelötet, läuft, Busverbindung steht! Ja was soll ich sagen lesen bildet. XD
Vielen Dank

Allerdings funktioniert die Nulleinspeisung genauso wenig wie bei BSG.
Händisch kann ich dien Wert vorgeben, die Kommunikation funktioniert also.
Nulleinspeisung steht auf Aktiv, Max. Watt bei 700Watt
Passieren tut daraufhin allerdings garnichts..

**Comment by TronTronix** [comment]
Also die Nulleinspeisung läuft eigentlich bei BSG es gib kleine Probleme
-	Anlaufströme
-	Die Übermittlung von Daten in Mqtt zum WeMos am besten in String schicken mit xx.00
-	Keine quelloffene Software
-	Weitere Software-Anomalien.

Das heißt jetzt für hier es gib generell ein Problem mit der Nulleinspeisung beim WeMos D1 mini bei dir.

**Und jetzt Brauchen wir einfach mehr Infos.**

Von wo kommen die Werte und welche Hardware ist verwendet worden, gibt es eine Software Anbindung und, und, und.

**Comment by matlen67** [comment]
Ich hole hier ja die Daten vom Shelly als Json und extrahiere daraus L1 L2 L3, siehe Funktion: int getMeterData(int type). Jetzt müsste ich halt wissen was Hitachi mit Tasmota liefert. Sonst kann die Nulleinspeisung natürlich nicht funktionieren.

**Comment by andibacken** [comment]
Meine Daten kommen von einem Shelly 3EM.
Der Verbrauch wird auch korrekt angezeigt.

Das merkwürdige ist.. es ist genau das selbe wie bei BSG.
Manuell hat funktioniert, Nullregelung nicht.

**Comment by matlen67** [comment]
Hast du beim Shelly auch die Phasen aktiviert die mit einberechnen soll?
![Screenshot 2024-09-08 075921](https://github.com/user-attachments/assets/4041ab81-e8b0-4f7e-9471-f5a979669758)

**Comment by andibacken** [comment]
Ja.

![Screenshot_2024-09-08-08-12-10-991_com android chrome](https://github.com/user-attachments/assets/49d298d4-0e5b-4a71-899b-13677bea9669)

**Comment by andibacken** [comment]
> Ja.
> 
> ![Screenshot_2024-09-08-08-12-10-991_com android chrome](https://private-user-images.githubusercontent.com/173003610/365417959-49d298d4-0e5b-4a71-899b-13677bea9669.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NzYyODksIm5iZiI6MTcyNTc3NTk4OSwicGF0aCI6Ii8xNzMwMDM2MTAvMzY1NDE3OTU5LTQ5ZDI5OGQ0LTBlNWItNGE3MS04OTliLTEzNjc3YmVhOTY2OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwNjEzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDkyNjU0MTNiYTZjNzk1MzQ4MDQ5Mjg2NzNiMDQ4YmYyNzcwY2JlNjVhMWM0NDk1ODYwYjE1YjA2OGU2MzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YWAAzEJFhmiXqEtqG9eR_Q5UhkhJebI0TlmnDB3MXNM)

Btw: den Output von 230 habe ich jetzt manuell gesetzt damit der Akku leer wird..

**Comment by matlen67** [comment]
Ich habe jetzt gerade keine Idee woran es liegen könnte. Diese Version läuft hier nun testweise auf meinem D1 mini clone, auch wenn der nicht in echt angeschlossen ist, versucht die Nulleinspeisung zu regeln. Der Soyo Output geht dann natürlich step by step auf max output, da der Soyo ja nicht wirklich einspeist.

**Comment by matlen67** [comment]
Ah was mir gerade auffällt. Du hast ja minusbezug also speist Du ja ein. Da benötigst Du ja auch kein Output vom Soyo. Der speist ja nur ein bei positiven Bezug aus dem Netz ein, damit du bei ca. 0 bist.

**Comment by TronTronix** [comment]
Ja genau das ist es, wer bringt den die Stromwerte in L1 soweit runter in Minus ist jetzt die frage.
Und warum nicht L2 oder L3 auf dem Bild.

**Comment by matlen67** [comment]
Alle Phasen werden ja zusammen gezählt (Zähler saldiert ja auch). Bsp. dein letzter Screenshot L1 = -134 / L2 = 0 / L3 = +123 macht = -11 Watt. Also werden noch 11 Watt eingespeist. Wenn jetzt der Soyo was ausgeben würde wäre das ja Sinnfrei, da verschenkt und zusätzlich mit eingespeist wird.

**Comment by andibacken** [comment]
Manchmal steht man mit dem Kopf auch direkt vor der Wand..

Ihr habt beide recht.. allerdings habe ich nicht eingespeist, sondern die Zangen vom Shelly waren verkehrt herum. Dementsprechend die gedrehten Werte.
Ich hätte Wetten können in der Anleitung stand es genauso drin.. K zum Netz. Pfeil/L zum Haus..

Nun sei es drum. Habe die Zangen gedreht und es funktioniert einwandfrei!

Vielen Dank!

**Comment by matlen67** [comment]
Sauber. Dann viel Spaß damit

**Comment by matlen67** [comment]
Dann mach ich hier dicht.

**Comment by matlen67** [comment]
Dann mach ich hier dicht.
